### PR TITLE
Change hk deliverable tag for coverage qc report

### PR DESCRIPTION
**Pull request by dnil**
### This PR:

Changed: hk delivery tag for coverage-qc-report

See e.g. https://github.com/Clinical-Genomics/hermes/pull/13 and https://github.com/Clinical-Genomics/cg/issues/987

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Review by hassanfa — APPROVED** [review]
👍🏽

**Comment by hassanfa** [comment]
@dnil I think this is the first piece to merge and deploy right?

**Comment by dnil** [comment]
Super! Yes - always start at the source! 😸

**Comment by hassanfa** [comment]
Thank you for fixing this.

**Pull request merged**
