### PR TITLE
feat: Option to use PON with TGA cnvkit

### PR DESCRIPTION
**Pull request by ashwini06**
### This PR:

Added: 
- Option to use PON reference (.cnn) if it is pre-existed while running TGA CNVkit **tumor-only** analysis. In the absence of PON reference file, the CNVkit workflow generates a Flatreference from genome files and uses it as a background

Removed: 
- Currently, sentieon TNhaplotyper tumor-only contains the option for using PON (.vcf), [this ](https://github.com/Clinical-Genomics/BALSAMIC/blob/f092cfe94005c0819108a2af5278fb8[…]ALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule)rule accept pon file from config, but cli changes for config that it could accept pon vcf file was never possible. Alternative option is to supply with `--snakemake-opt` to add extra config keys. Anyways compared to existing downstream filters, PoN isn’t improving performance for SNV calling. So decision to remove this option - @hassanfa @ashwini06 

### Review and tests: 
- [x] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by ashwini06** [comment]
Although added the relevant test code lines, code coverage complains of missing [one test line ](https://app.codecov.io/gh/Clinical-Genomics/BALSAMIC/compare/851/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr%20comments&utm_term=Clinical-Genomics#diff-QkFMU0FNSUMvY29tbWFuZHMvcnVuL2FuYWx5c2lzLnB5). Although its a slight drop of -0.06%, can be safely ignored

**Comment by ashwini06** [comment]
@ivadym @khurrammaqbool: Ready for review of this PR :)

**Comment by khurrammaqbool** [comment]
> Although added the relevant test code lines, code coverage complains of missing [one test line ](https://app.codecov.io/gh/Clinical-Genomics/BALSAMIC/compare/851/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr%20comments&utm_term=Clinical-Genomics#diff-QkFMU0FNSUMvY29tbWFuZHMvcnVuL2FuYWx5c2lzLnB5). Although its a slight drop of -0.06%, can be safely ignored

`codecov/patch Failing after 1s — 87.50% of diff hit (target 99.60%)`should it be matter of concern?

**Comment by ashwini06** [comment]
@khurrammaqbool : Pon_cnn path is moved to panel dict from analysis 

Test config file located here: `/home/proj/long-term-stage/cancer/PON_analysis_runs_APJ/PON_test_datasets/test_safegrouse_ponrun2/test_safegrouse_ponrun2.json`

Screenshot 2022-03-28 at 18 11 19

**Review by keyvanelhami — APPROVED** [review]

**Review by ivadym — APPROVED** [review]
Thanks @ashwini06 for making the changes 👍

**Pull request merged**
