### PR TITLE
fix: edit sample names in germline dnascope vcf for genotype

### PR DESCRIPTION
**Pull request by ashwini06**
### This PR:

Fixes: https://github.com/Clinical-Genomics/BALSAMIC/issues/882

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by ashwini06** [comment]
@ivadym : Can you please check if the housekeeper tags are correct? Also I haven't added the new rule to https://github.com/Clinical-Genomics/BALSAMIC/blob/1a7740fa5b3a24a7fa4bac160934e20366c693c8/BALSAMIC/constants/workflow_rules.py#L117
in the thought that this file will not be delivered to the customer and just be stored for our internal purpose in HK

**Comment by ashwini06** [comment]
**Test runs:** 

located here `/home/proj/stage/cancer/cases/unitedbeagle_genotype/analysis/vep`

DNAscope output file with `NORMAL` in the header: `SNV.germline.normal.dnascope.vcf.gz` 
Screenshot 2022-06-17 at 16 53 22

New DNAscope output file for genotype with `ACC6225A14` in the header: `SNV.germline.normal.dnascope.vcf.gz` 

Screenshot 2022-06-17 at 16 54 09

**Review by ivadym — CHANGES_REQUESTED** [review]
Great solution @ashwini06! Some minor comments:

> in the thought that this file will not be delivered to the customer and just be stored for our internal purpose in HK

What is stored/delivered is decided in Hermes and CG from the `.hk` file generated by BALSAMIC. So we need to add `vcfheader_rename_germline` to `DELIVERY_RULES` if we want to use this file upstream.

**Comment by ashwini06** [comment]
> Great solution @ashwini06! Some minor comments:
> 
> > in the thought that this file will not be delivered to the customer and just be stored for our internal purpose in HK
> 
> What is stored/delivered is decided in Hermes and CG from the `.hk` file generated by BALSAMIC. So we need to add `vcfheader_rename_germline` to `DELIVERY_RULES` if we want to use this file upstream.

Fixed in https://github.com/Clinical-Genomics/BALSAMIC/pull/958

**Review by ivadym — APPROVED** [review]
Looks good 🎈

**Pull request merged**
