### PR TITLE
fix: docs importing C dependant libraries

### PR DESCRIPTION
**Pull request by ivadym**
### This PR:

Adresses `ModuleNotFoundError: No module named 'numpy'` when building the docs:
https://readthedocs.org/projects/balsamic/builds/16287901/

Solution from:
https://read-the-docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Review by ashwini06 — APPROVED** [review]
👍🏼

**Comment by ivadym** [comment]
I also added `setup.py` requirements installation to the sphinx github action

**Comment by ashwini06** [comment]
> I also added `setup.py` requirements installation to the sphinx github action

Looks like all setup.py packages are properly installed with sphinx git action. But there are also differences in the sphinx versions used by our docs/requiremen.txt (sphinx==4.2.0) and the one used in git actions (https://github.com/ammaraskar/sphinx-action/blob/master/.travis.yml). Does this something to think about?

**Comment by ivadym** [comment]
I don't think so because the problem is actually not with Sphinx, but with compiling the Sphinx documentation with ReadTheDocs, which does not allow having `numpy` as a requirement:
> ...
This happens because our build system doesn’t have the dependencies for building your project. This happens with things like libevent, mysql, and other python packages that depend on C libraries. **We can’t support installing random C binaries on our system**, ...
...

**Pull request merged**
