### PR TITLE
Hotfix/ bump cosmic to v94

### PR DESCRIPTION
**Pull request by hassanfa**
### This PR:

Changed:

- Bumped cosmic version 94 and a valid path

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Review by khurrammaqbool — COMMENTED** [review]
It may be nice to have an issue describing the authentication problem and the solution for future reference.

**Comment by hassanfa** [comment]
> It may be nice to have an issue describing the authentication problem and the solution for future reference.

Still waiting for COSMIC support. I do not know if it is an authentication issue or not. Anyway, the reference needed to be updated as well. It is not a critical annotation, we might as well bump it.

**Review by khurrammaqbool — APPROVED** [review]

**Comment by hassanfa** [comment]
Forgot to screenshot and paste it here... I started the test run again.. 🤦🏽

**Comment by hassanfa** [comment]
Download finished successsfully: 
image

**Pull request merged**
