### PR TITLE
Refactor BALSAMIC packaging

### PR DESCRIPTION
**Pull request by hassanfa**
### This PR:

- Fixes BALSAMIC packaging

### How to test:

- Automatic and continuous test pass

### Expected outcome:

- Installation, unit and integration tests pass

### Review:
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by hassanfa** [comment]
@moonso here is the solution I was explaining today. Probably `cg.utils.Process` should also have an option to append a command via `sys.exectuable`. But for now fixing it in BALSAMIC.

**Comment by hassanfa** [comment]
image

Tests ok.

**Comment by moonso** [comment]
I thought you would be onsite today @hassanfa , but show me the solution next time we meet!

**Comment by hassanfa** [comment]
I will be after lunch :-). I have a meeting that needs preparation.

**Pull request merged**
