### PR TITLE
cnvkit refactor changelog

### PR DESCRIPTION
**Pull request by ashwini06**
### This PR:

By mistake I pushed my recent code on refactoring cnvkit command to develop branch directly
Related commits are:  7b648dde7d6ffe90155afc775aa98f1d261eed00 and afc17e50f385e5d25e96644779a4c8d37812a458
Issue related to https://github.com/Clinical-Genomics/cgp-cancer-cnvcall/issues/15

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by hassanfa** [comment]
Lets leave comments here: :-D 

1. In `balsamic.smk` we should also remove CNV from WGS here:
https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/workflows/balsamic.smk#L204 and for single mode WGS as well.

2. Could you please add comment for each section of `shell:` in https://github.com/Clinical-Genomics/BALSAMIC/commit/7b648dde7d6ffe90155afc775aa98f1d261eed00 ? Looks like shell is a bit too large, and it'll be nice to know what each part does.

3. Can you create an issue to update deliveries for CNV part with these changes? Since we are removing WGS, CNV will not exist there anymore for now, and we will have new files to deliver.

Otherwise looks good!

**Review by hassanfa — CHANGES_REQUESTED** [review]
left review as comment with two change requests.

**Comment by hassanfa** [comment]
Also please update Changelog to mention WGS doesn't have CNV kit anymore.

**Comment by ashwini06** [comment]
Thanks @hassanfa, fixed your comments. Please have a look.

> 1. In `balsamic.smk` we should also remove CNV from WGS here:
>    https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/workflows/balsamic.smk#L204 and for single mode WGS as well.  - **Done** 
> 2. Could you please add comment for each section of `shell:` in [7b648dd](https://github.com/Clinical-Genomics/BALSAMIC/commit/7b648dde7d6ffe90155afc775aa98f1d261eed00) ? Looks like shell is a bit too large, and it'll be nice to know what each part does. - **Done** 
> 3. Can you create an issue to update deliveries for CNV part with these changes? Since we are removing WGS, CNV will not exist there anymore for now, and we will have new files to deliver. -
 Create new issue here : https://github.com/Clinical-Genomics/cgp-cancer-cnvcall/issues/17

**Review by hassanfa — APPROVED** [review]
👍🏽

**Pull request merged**
