### PR TITLE
fix: Number of variants increased with inclusion of triallelic_sites

### PR DESCRIPTION
**Pull request by khurrammaqbool**
### This PR:

Fixed: Number of variants increased with inclusion of triallelic_sites

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by khurrammaqbool** [comment]
## civilsole (WGS-TO) 

## clinical filtered pass
   Number of samples: 1
   Number of SNPs:    29065
   Number of INDELs:  4366
   Number of MNPs:    0
   Number of others:  0
   Number of sites:   33431
## research filtered pass
  Number of samples: 1
  Number of SNPs:    29454
  Number of INDELs:  4902
  Number of MNPs:    0
  Number of others:  0
  Number of sites:   34356

**Comment by fevac** [comment]
Great! ⭐  What filtering did you do at the end? I'm not as fluent with bcftools so I don't fully follow

**Comment by khurrammaqbool** [comment]
> Great! ⭐ What filtering did you do at the end? I'm not as fluent with bcftools so I don't fully follow

I same filters, `PASS` and `triallelic_site`, are added as an expression. 

The text below is taken from the documentation of `bcftools` that explains it
`include only sites for which EXPRESSION is true`

The documentation of `bcftools` is a great resource to become "fluent" with it.
https://samtools.github.io/bcftools/bcftools.html

**Comment by mathiasbio** [comment]
If I understood the changes of the filtering correctly this will mean that variants with either PASS or only the triallelic_site filter set will be kept in the final vcf. Using the -f flag instead would also keep variants with the triallelic_site filter even if they had in addition other filters set. This sounds like the fix implemented the original intended filtering strategy!

**Review by mathiasbio — APPROVED** [review]
Looks like the fix should work as intended! Nice job : )

**Pull request merged**
