### PR TITLE
feat: generate umi cram files

### PR DESCRIPTION
**Pull request by ashwini06**
### This PR:

Added: Generates CRAM files from UMI-consensus called bam files. Related to #865 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by ashwini06** [comment]
@ivadym @khurrammaqbool anyone review this PR? @ivadym: umi cram files should be stored in HK, will you make necessary related changes in Hermes?

**Review by khurrammaqbool — APPROVED** [review]

**Review by ivadym — CHANGES_REQUESTED** [review]
Just two things:

-  A housekeeper id should be added to the rules in order for the cram files to be stored. If you add a wildcard to the output file it will be also treated as a tag.
```
params:
        housekeeper_id = {"id": config["analysis"]["case_id"], "tags": " ... "}
```

- If we don't want to store bam files, then the bam output file should be marked as `tmp`, right? I can also just ignore it in Hermes, but with this implementation it will appear in the `.hk` file.

**Review by ivadym — APPROVED** [review]
👍

I'll make the corresponding changes in Hermes to store themö

**Comment by ashwini06** [comment]
> 👍
> 
> I'll make the corresponding changes in Hermes to store them.


Thanks @ivadym. For a reason, I didn't mark the `"tumor_umi_consensusfiltered.merged.bam"` and `_consensuscalled.bam` as `temp`. But you know only the UMI cram's should be stored and rest (umi related bams) can be ignored in HK.

**Pull request merged**
