### PR TITLE
Hotfix - simplify delivery and correct file id

### PR DESCRIPTION
**Pull request by hassanfa**
### This PR:

Changed:
- only pass variants are not part of delivery anymore
- delivery tag file ids are properly matched with sample_name

Removed:
- sentieon-dedup rule from delivery

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by hassanfa** [comment]
tests are failing, i'll look into as well.

**Comment by hassanfa** [comment]
@ashwini06 any more comments on this? ready to be merged.

**Review by ashwini06 — COMMENTED** [review]
Look good 👍

**Comment by ashwini06** [comment]
> @ashwini06 any more comments on this? ready to be merged.

Tests for few lines in cli are missing, with those I think its good to merge

**Review by ashwini06 — COMMENTED** [review]
👍

**Pull request merged**
