### PR TITLE
perf: COSMIC database to v97 

### PR DESCRIPTION
**Pull request by ivadym**
###
- Update cosmicdb to v97

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by ivadym** [comment]
Tested the availability and download of the vcf in: https://github.com/Clinical-Genomics/BALSAMIC/pull/1117

**Review by mathiasbio — COMMENTED** [review]
Looks good! : ) Have you tested running it on a case and seeing if the cosmic annotations are there?

**Comment by ivadym** [comment]
Good idea 👍

**Comment by ivadym** [comment]
Looks good @mathiasbio 

v97 database
Screenshot 2023-04-26 at 09 18 40

annotated variants
Screenshot 2023-04-26 at 09 20 04

**Review by mathiasbio — APPROVED** [review]

**Pull request merged**
