### PR TITLE
build: Update env requirements for containers

### PR DESCRIPTION
**Pull request by fevac**
### This PR:

Updates containers specifications by explicitly setting versions for all dependencies. 

Related to: https://github.com/Clinical-Genomics/BALSAMIC/issues/1061

**Note:**
- Requirements for balsamic container might be problematic since the balsamic version cannot be specified as it will be changing. If this is actually the case and errors often arise, we might want to revert the specifications in this container back to the minimal settings. 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by fevac** [comment]
**NOTE**

When exporting an environment with `conda env export` it adds a platform-specific version tag. This will be problematic when switching between platforms (eg. mac and linux). To avoid including the build tags in conda environment files we should export using `conda env export --no-builds` instead.

**Comment by ivadym** [comment]
It will also be nice to see and compare how long it takes to install them and if we see an improvement there as well

**Comment by fevac** [comment]
I'm officially giving up on this pytest errors (which I also get locally and I don't think they are container related??). I'll put this on hold for now and check further once I have more time again.

**Comment by fevac** [comment]
Closing in favour of https://github.com/Clinical-Genomics/BALSAMIC/pull/1096

**Pull request closed without merging**
