### PR TITLE
fix: multiline character in VEP rule

### LINKED ISSUE #734: VEP command incorrect multiline shell command
**Describe the bug**
Bug introduced in 8.0.0 release, where multiline command: https://github.com/Clinical-Genomics/BALSAMIC/blob/08cb913ec09e919c7510f322c770e0a50a2228ad/BALSAMIC/snakemake_rules/annotation/vep.rule#L50-L55
which used to be https://github.com/Clinical-Genomics/BALSAMIC/blob/675fcb9374458a0810964e7dbcb6f0c7a255737a/BALSAMIC/snakemake_rules/annotation/vep.rule#L51-L55

**To Reproduce**
Any runs after `8.X.X`

**Expected behavior**
Shell command in VEP rule to exit successfully.

**If workflow, which rules**
vep_somatic and vep_germline

**Screenshots**
N/A

**Version (please complete the following information):**
`8.0.1`

**Additional context**
None.

### PR DESCRIPTION
**Pull request by hassanfa**
### This PR:

Fixed:
- replaced multiline `\` with `;` in VEP rules. fixes #734 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Review by ivadym — APPROVED** [review]
👏👏

**Review by ashwini06 — APPROVED** [review]
Good catch :mag: :pencil2:

**Comment by hassanfa** [comment]
> Good catch 🔍 ✏️

Actually, Vadym found it :-)

**Review by khurrammaqbool — APPROVED** [review]
👍

**Comment by hassanfa** [comment]
This is directly from master to master. So i'm squash merging.

**Pull request merged**
