### PR TITLE
feat: add clinvar as a source of annotation

### LINKED ISSUE #737: Annotate somatic variants from ClinVar
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/Clinical-Genomics/scout/issues/2836 ClinVar review status is missing in final VCF file.

**Describe the solution you'd like**
- Download ClinVar from https://ftp.ncbi.nlm.nih.gov/pub/clinvar/
- Annotate at vep_somatic and vep_germline stage

**Describe alternatives you've considered**
Rely solely on VEP, but then we will miss review status tag

**Additional context**
None.

**Expected output for the feature**
Following tags exist in INFO of final VCF:
1. CLNACC
2. CLNREVSTAT
3. CLNSIG
4. ORIGIN
5. CLNVC
6. CLNVCSO

**Current BALSAMIC version**
`8.0.2`

### PR DESCRIPTION
**Pull request by hassanfa**
### This PR:

Added:
- ClinVar as a source of annotation. fixes #737 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by hassanfa** [comment]
I started a test run and analysis for this.

**Review by ashwini06 — APPROVED** [review]
Looks good💯  Will be interesting to see how these clinvar tags are added to the info in the new vcf file. Can you please paste a screenshot after you have the test result run?

**Comment by hassanfa** [comment]
> Looks good💯 Will be interesting to see how these clinvar tags are added to the info in the new vcf file. Can you please paste a screenshot after you have the test result run?

Will do.

**Comment by hassanfa** [comment]
Final JSON with Clinvar's successful download:
image

**Comment by hassanfa** [comment]
Clinvar annotation in output: 
image

**Pull request merged**
