### PR TITLE
chore: Update add-to-bl action

### PR DESCRIPTION
**Pull request by pbiology**
### This PR:

Updates the github action which adds issues to the project. 
Just future proofing since I noticed it was a bit out of date.

### CODE REVIEW

**Comment by pbiology** [comment]
Can we do this without bumping the version?

**Comment by pbiology** [comment]
Actually it is not very urgent at all so perhaps it can just be part of next release

**Review by ivadym — APPROVED** [review]
Nice 👍  

We've been fixing deliberately the ubuntu version, but I suppose here it's fine to use `ubuntu-latest`

**Comment by pbiology** [comment]
> Nice 👍
> 
> We've been fixing deliberately the ubuntu version, but I suppose here it's fine to use `ubuntu-latest`

Yeah I wasn't sure. I saw that in cg, servers etc ubuntu-latest was used. I guess to avoid an old version being deprecated. But I'm honestly not sure what is the best practice

**Comment by ivadym** [comment]
Probably for the containers it's better to use a fixed version, but for the rest of the actions I think it's ok to use the latest

**Comment by khurrammaqbool** [comment]
> > Nice 👍
> > We've been fixing deliberately the ubuntu version, but I suppose here it's fine to use `ubuntu-latest`
> 
> Yeah I wasn't sure. I saw that in cg, servers etc ubuntu-latest was used. I guess to avoid an old version being deprecated. But I'm honestly not sure what is the best practice

To my experience it is always nice to fix the OS version for docker container. For github actions, using latest is fine in case the action/repository is actively maintained. So it should be fine for most of the common repos to use `ubuntu-latest`.

**Comment by ivadym** [comment]
Closing as the container version has already been updated in another PR

**Pull request closed without merging**
