### PR TITLE
feat: release v11.1.0

### PR DESCRIPTION
**Pull request by fevac**
### This PR:

New release of BALSAMIC v11.1.0

Added:
^^^^^^
* Added somalier integration and relatedness check: https://github.com/Clinical-Genomics/BALSAMIC/pull/1017
* Cluster resources for CNVPytor tumor only https://github.com/Clinical-Genomics/BALSAMIC/pull/1083

Changed:
^^^^^^^^
* Parallelize download of reference files https://github.com/Clinical-Genomics/BALSAMIC/pull/1065
* Parallelize download of container images https://github.com/Clinical-Genomics/BALSAMIC/pull/1068

Fixed:
^^^^^^
* triallelic_site in quality filter for SNV https://github.com/Clinical-Genomics/BALSAMIC/pull/1052
* Compression of SNV, research and clinical, VCF files https://github.com/Clinical-Genomics/BALSAMIC/pull/1060 
* `test_write_json` failing locally https://github.com/Clinical-Genomics/BALSAMIC/pull/1063
* Container build and push via github actions by setting buildx `provenance` flag to false https://github.com/Clinical-Genomics/BALSAMIC/pull/1071
* Added buildx to the submodule workflow https://github.com/Clinical-Genomics/BALSAMIC/pull/1072
* Change user in somalier container to defaultuser https://github.com/Clinical-Genomics/BALSAMIC/pull/1080
* Reference files for hg38 https://github.com/Clinical-Genomics/BALSAMIC/pull/1081

### Tests carried out:
- [ ] Containers are pulled correctly from docker hub via singularity
- [ ] Reference download parallelisation works
- [ ] Container download parallelisation works
- [ ] FLT3.ITD300 is not filtered out
- [ ] Compression of SNV, research and clinical, VCF files
- [ ] Reference files for hg38 has been updated
- [ ] Somalier relatedness metric retrieval and QC pass
- [ ] Somalier QC fail 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by fevac** [comment]
@ivadym what do you think about the security hotspot? Should we aim to add and set a non-root default user? It could possibly be done by:
```
FROM alpine:3.11.5
RUN adduser -D defaultuser
USER defaultuser
```

**Comment by ivadym** [comment]
> @ivadym what do you think about the security hotspot? Should we aim to add and set a non-root default user? It could possibly be done by:
> 
> ```
> FROM alpine:3.11.5
> RUN adduser -D defaultuser
> USER defaultuser
> ```

Sounds good! As I understand this security hotspot, if someone currently imports these Dockerfiles they will act as root users by default so probably it's good to address it

**Comment by fevac** [comment]
@ivadym I could not test using the S_balsamic environment as I was having problems with it and ran the previous tests with my own balsamic environment. Do you think we should run a quick test using S_balsamic or not needed?

**Comment by fevac** [comment]
I think we should aim to add this PR https://github.com/Clinical-Genomics/BALSAMIC/pull/1052 here as it was required from the previous validation

**Comment by ivadym** [comment]
> @ivadym I could not test using the S_balsamic environment as I was having problems with it and ran the previous tests with my own balsamic environment. Do you think we should run a quick test using S_balsamic or not needed?

 💯  💯 

Yes, I have also found some issues installing specific versions on it, but I managed to bypass it by completely reinstalling it (we always use hiseq clinical btw).

And seems that you have tested it with your environment and it went fine, so we can just do it again after the release (before deployment) with the new containers in stage I would say 👍

**Review by ivadym — APPROVED** [review]
👍

**Comment by fevac** [comment]
**QC warnings from tests:**

- civilsole
  - QC metric PCT_60X: 0.004532 validation has failed. (Condition: gt 0.8, ID: ACC7204A2). (type=value_error)
  - QC metric NUMBER_OF_SITES: 158885 validation has failed. (Condition: lt 50000.0, ID: civilsole). (type=value_error) 
- fleetjay
  - QC metric PCT_60X: 0.00836 validation has failed. (Condition: gt 0.8, ID: ACC5821A7). (type=value_error)
- closetuna
  -   QC metric PCT_60X: 0.004532 validation has failed. (Condition: gt 0.8, ID: ACC7204A2). (type=value_error)
  -   QC metric NUMBER_OF_SITES: 53816 validation has failed. (Condition: lt 50000.0, ID: closetuna). (type=value_error)
  -   QC metric RELATEDNESS: -0.03 validation has failed. (Condition: gt 0.8, ID: closetuna). (type=value_error)
- setamoeba
- uphippo
  -   QC metric PCT_TARGET_BASES_1000X: 0.861996 validation has failed. (Condition: gt 0.95, ID: ACC5611A3). (type=value_error)
  -   QC metric GC_DROPOUT: 1.650392 validation has failed. (Condition: lt 1.0, ID: ACC5611A3). (type=value_error)
- unitedbeagle
- equalbug
  -   QC metric GC_DROPOUT: 1.087643 validation has failed. (Condition: lt 1.0, ID: ACC7363A2). (type=value_error)
  -   QC metric RELATEDNESS: -0.524 validation has failed. (Condition: gt 0.8, ID: equalbug). (type=value_error)

**Pull request merged**
