### PR TITLE
fix: missing vep_install and add container specific tests

### LINKED ISSUE #768: Problems running vep_install with develop-annotate container
Reference generation with using `develop` container exits on `vep_install` job 

red

Problems 
While building `develop-annotate` container, conda failed with vep installation

vep

### PR DESCRIPTION
**Pull request by hassanfa**
### This PR:

- Fixes #768 for missing vep_install command
- Adds container specific tests

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by hassanfa** [comment]
Tests already fail successfully when command is not found in the container. Example: 
image

Correct cnvkit command is cnvkit.py

**Comment by hassanfa** [comment]
Also pass when commands are found: 
image

**Comment by hassanfa** [comment]
vep_install is also there: 
image

**Review by ashwini06 — APPROVED** [review]
Cool.. you added up some tests for container 💯

**Pull request merged**
