### PR TITLE
Fix/ids panel tumor

### PR DESCRIPTION
**Pull request by Mropat**
### This PR:

Additional sample_name tags for panel runs

Fixed: panel deliverables on real data did not get sample_name tag 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by Mropat** [comment]
bundle now has sample_name tags
image

**Comment by Mropat** [comment]
codecof vailing because there are fewer lines :S

**Comment by hassanfa** [comment]
Looks good.

So I was right after all a test on actual sample should have been done 😆

1. Please fix title
2. Please post "**screenshot**" of cases that you have tested here

**Comment by hassanfa** [comment]
Nevermind on title. My browser showed it empty 😳😳

**Pull request merged**
