### PR TITLE
feat: bcftools counts QC validation

### PR DESCRIPTION
**Pull request by ivadym**
### This PR:

Added a new metric to be extracted and validated: `NUMBER_OF_SITES`.

- It will be included in the `<case>_metrics_deliverables.yaml` file.
- A threshold of `10000` number of variants has been chosen.

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by ivadym** [comment]
### Tested on a `TN_PANEL` case:

#### Valid number of variants condition:
<details>
<summary>case_metrics_deliverables.yaml</summary>

```
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_OFF_BAIT
  step: multiqc_picard_HsMetrics
  value: 0.161177
  condition: null
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.hsmetric
  name: MEAN_TARGET_COVERAGE
  step: multiqc_picard_HsMetrics
  value: 636.240492
  condition: null
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.hsmetric
  name: MEDIAN_TARGET_COVERAGE
  step: multiqc_picard_HsMetrics
  value: 597.0
  condition:
    norm: gt
    threshold: 500.0
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.hsmetric
  name: FOLD_80_BASE_PENALTY
  step: multiqc_picard_HsMetrics
  value: 1.469378
  condition:
    norm: lt
    threshold: 1.8
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_50X
  step: multiqc_picard_HsMetrics
  value: 0.998388
  condition: null
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_100X
  step: multiqc_picard_HsMetrics
  value: 0.99497
  condition: null
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_250X
  step: multiqc_picard_HsMetrics
  value: 0.965734
  condition: null
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_500X
  step: multiqc_picard_HsMetrics
  value: 0.679447
  condition: null
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_1000X
  step: multiqc_picard_HsMetrics
  value: 0.085215
  condition: null
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_OFF_BAIT
  step: multiqc_picard_HsMetrics
  value: 0.158228
  condition: null
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.hsmetric
  name: MEAN_TARGET_COVERAGE
  step: multiqc_picard_HsMetrics
  value: 888.363409
  condition: null
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.hsmetric
  name: MEDIAN_TARGET_COVERAGE
  step: multiqc_picard_HsMetrics
  value: 805.0
  condition:
    norm: gt
    threshold: 500.0
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.hsmetric
  name: FOLD_80_BASE_PENALTY
  step: multiqc_picard_HsMetrics
  value: 1.566778
  condition:
    norm: lt
    threshold: 1.8
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_50X
  step: multiqc_picard_HsMetrics
  value: 0.998554
  condition: null
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_100X
  step: multiqc_picard_HsMetrics
  value: 0.997177
  condition: null
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_250X
  step: multiqc_picard_HsMetrics
  value: 0.979765
  condition: null
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_500X
  step: multiqc_picard_HsMetrics
  value: 0.874605
  condition: null
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.hsmetric
  name: PCT_TARGET_BASES_1000X
  step: multiqc_picard_HsMetrics
  value: 0.304366
  condition: null
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.insertsizemetric
  name: MEAN_INSERT_SIZE
  step: multiqc_picard_insertSize
  value: 125.820417
  condition: null
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.insertsizemetric
  name: MEAN_INSERT_SIZE
  step: multiqc_picard_insertSize
  value: 131.28036
  condition: null
- header: null
  id: ACC6225A18
  input: concatenated_ACC6225A18_XXXXXX_R.sorted.mrkdup.txt
  name: PERCENT_DUPLICATION
  step: multiqc_picard_dups
  value: 0.356236
  condition: null
- header: null
  id: ACC6225A14
  input: concatenated_ACC6225A14_XXXXXX_R.sorted.mrkdup.txt
  name: PERCENT_DUPLICATION
  step: multiqc_picard_dups
  value: 0.255699
  condition: null
- header: null
  id: unitedbeagle
  input: SV.somatic.unitedbeagle.svdb.all.filtered.pass.stats
  name: NUMBER_OF_SITES
  step: collect_custom_qc_metrics
  value: 16
  condition:
    norm: lt
    threshold: 10000.0
- header: null
  id: unitedbeagle
  input: SNV.somatic.unitedbeagle.vardict.all.filtered.pass.stats
  name: NUMBER_OF_SITES
  step: collect_custom_qc_metrics
  value: 233
  condition:
    norm: lt
    threshold: 10000.0
- header: null
  id: unitedbeagle
  input: SNV.somatic.unitedbeagle.TNscope_umi.all.filtered.pass.stats
  name: NUMBER_OF_SITES
  step: collect_custom_qc_metrics
  value: 0
  condition:
    norm: lt
    threshold: 10000.0
```
</details>

#### Condition set to `1.0` -> validation fails:

Screen Shot 2022-05-02 at 11 42 30

**Review by khurrammaqbool — APPROVED** [review]
💯

**Review by ashwini06 — APPROVED** [review]
Looks great 🥇

**Comment by ivadym** [comment]
Thanks @ashwini06 and @khurrammaqbool for your reviews!

**Pull request merged**
