### PR TITLE
feat: Store TMB files in HK

### PR DESCRIPTION
**Pull request by ivadym**
### This PR:

It has been decided to start storing Balsamic TMB files in HK.

Hermes PR: https://github.com/Clinical-Genomics/hermes/pull/71/files

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by ivadym** [comment]
Maybe we could also include this small PR in v12? What do you think @Clinical-Genomics/cancer-bioinfo?

**Comment by pbiology** [comment]
I would say yes. This has no effect on the analysis

**Comment by pbiology** [comment]
I do think that for any feature we add, we should run at least a case to show that the pipeline as a whole still works.

**Comment by ivadym** [comment]
`> balsamic report deliver -s civilsole.json `
Screenshot 2023-04-27 at 09 15 41

`.hk file`
Screenshot 2023-04-27 at 09 17 31

**Review by mathiasbio — APPROVED** [review]
Looks good! And with the successful test, I hereby give my stamp of approval on this PR. Well done! 🌟

**Pull request merged**
