### PR TITLE
adding cyvcf2 and cython to requirements

### PR DESCRIPTION
**Pull request by ashwini06**
**### This PR:**

Remove cyvcf2 and Cython from `.travis.yml` and adds those dependencies to `requirements.txt` 
Remove conda dependencies for cyvcf2 from `BALSAMIC/conda/balsamic.yaml`

**Problem:**
Removal of `pip install cython and cyvcf2` from `.travis.yml` results in travis build failure

**Solution:**

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by hassanfa** [comment]
Thanks for looking into this. 👍

**Comment by ashwini06** [comment]
No pre-existence of `cyvcf2` in conda environment

a1

Install via `pip install -r requirements.txt -e .`
Screenshot 2020-09-11 at 13 47 35

**Comment by hassanfa** [comment]
beautiful and quick fix.

**Review by hassanfa — APPROVED** [review]

**Comment by hassanfa** [comment]
Please merge it whenever you're happy with the result.

**Pull request merged**
