### PR TITLE
feat: update PON workflow

### PR DESCRIPTION
**Pull request by ivadym**
### Added
* Added PON version to CLI and `config.json`

### Removed
* case ID from the PON `.cnn` output file

---

### Tested:
`balsamic run analysis --account development --mail-user clinical.delivery.cancer@scilifelab.se --qos normal --sample-config /home/proj/stage/cancer/cases/moreboa/moreboa_PON.json --benchmark`

Screen Shot 2022-07-26 at 16 55 32

Screen Shot 2022-07-27 at 10 52 01

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by ivadym** [comment]
Ready to be reviewed @khurrammaqbool 😄

**Comment by khurrammaqbool** [comment]
I suggest adding a separate section in the docs to explain the method and details on how to generate and use the cnvkit_PON.

**Comment by ivadym** [comment]
I updated the docs but I'm not sure if it will be enough for the customers, maybe @moahaegglund can complement this documentation afterwards. Tell me what you think and if you are missing something. The documentation for prod bioinfo is on [atlas](https://github.com/Clinical-Genomics/atlas/pull/868).

Screen Shot 2022-07-28 at 11 32 27

**Review by khurrammaqbool — APPROVED** [review]
👍

**Pull request merged**
