### PR TITLE
fix: removed libreadline.so symlinking, and fixed R version to 3.6.2 for varcall_py36 container

### LINKED ISSUE #739: varcall_py36 is missing libreadline.so.6
**Describe the bug**
The varcall_py36 container is missing the libreadline.so.6 library when calling the vardict_tumor_normal rule (somatic_tumor_normal.rule).

**To Reproduce**
Executed run_validate script (stage cache).

**Log**
```
source activate varcall_py36;
mkdir -p /home/vadym.ivanchuk/Projects/BALSAMIC/dummy_test_20210901/TN_panel/analysis/tmp/w1xp7lun;
export TMPDIR=/home/vadym.ivanchuk/Projects/BALSAMIC/dummy_test_20210901/TN_panel/analysis/tmp/w1xp7lun;
export VAR_DICT_OPTS='"-Djava.io.tmpdir=/home/vadym.ivanchuk/Projects/BALSAMIC/dummy_test_20210901/TN_panel/analysis/tmp/w1xp7l
un" "-Xmx32G"';

vardict-java -U -u -I 600 -G /home/proj/stage/cancer/balsamic_cache/8.0.2/hg19/genome/human_g1k_v37.fasta -f 0.001 -N TN_panel 
-b "/home/vadym.ivanchuk/Projects/BALSAMIC/dummy_test_20210901/TN_panel/analysis/bam/tumor.merged.bam|/home/vadym.ivanchuk/Proj
ects/BALSAMIC/dummy_test_20210901/TN_panel/analysis/bam/normal.merged.bam" -th 10 -c 1 -S 2 -E 3 -g 4 /home/vadym.ivanchuk/Proj
ects/BALSAMIC/dummy_test_20210901/TN_panel/analysis/vcf/split_bed/4.panel.bed | testsomatic.R | var2vcf_paired.pl -P 0.9 -m 4.5
 -M -f 0.001 -N TN_panel | bgzip > /home/vadym.ivanchuk/Projects/BALSAMIC/dummy_test_20210901/TN_panel/analysis/vcf/vardict/spl
it_vcf/4_vardict.vcf.gz;

tabix -p vcf /home/vadym.ivanchuk/Projects/BALSAMIC/dummy_test_20210901/TN_panel/analysis/vcf/vardict/split_vcf/4_vardict.vcf.g
z;
rm -rf /home/vadym.ivanchuk/Projects/BALSAMIC/dummy_test_20210901/TN_panel/analysis/tmp/w1xp7lun;
    
Activating singularity image /home/proj/stage/cancer/balsamic_cache/8.0.2/containers/varcall_py36.sif
/.singularity.d/actions/exec: /.singularity.d/env/10-docker2singularity.sh: line 1: ash\: not found
/opt/conda/envs/varcall_py36/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared objec
t file: No such file or directory
```

**Additional context**
```
singularity exec varcall_py36.sif find /opt/conda/lib -name libreadline*
/opt/conda/lib/libreadline.so
/opt/conda/lib/libreadline.so.8
/opt/conda/lib/libreadline.so.8.0
```

**Version**
BALSAMIC version 8.0.2

### PR DESCRIPTION
**Pull request by hassanfa**
### This PR:

Fixed:
- Removed libreadline linking, and fixed R version to 3.6.2 fixes #739 

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Comment by hassanfa** [comment]
Previous container erorr:
image

After this fix:
image

**Comment by hassanfa** [comment]
Essentially R was the culprit here...

**Comment by ashwini06** [comment]
Dont forget to check this align_qc container `https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/containers/align_qc/align_qc.sh`. Did someone checked if its working fine?

**Comment by hassanfa** [comment]
align_qc is also functional, built locally and tested:

image

**Review by ashwini06 — APPROVED** [review]

**Pull request merged**
