### PR TITLE
Decouple containers into their own definition

### PR DESCRIPTION
**Pull request by hassanfa**
### This PR:

Changed:
- Decouple and move away from single container to multiple container

### Review and tests: 
- [ ] Tests pass
- [ ] Code review
- [ ] New code is executed and covered by tests, and test approve

### CODE REVIEW

**Review by ashwini06 — COMMENTED** [review]
Nice 👍
 Can you also include sentieon installation to docker?

**Comment by hassanfa** [comment]
> Nice 👍
> Can you also include sentieon installation to docker?

Good point! I'll add that as well. I think we can add all three versions: 2018, 2019, and 2020. What do you think?

**Comment by ashwini06** [comment]
> > Nice 👍
> > Can you also include sentieon installation to docker?
> 
> Good point! I'll add that as well. I think we can add all three versions: 2018, 2019, and 2020. What do you think?

Cool. But are we using the 2018 version for any specific analysis?

**Comment by hassanfa** [comment]
> > > Nice 👍
> > > Can you also include sentieon installation to docker?
> > 
> > Good point! I'll add that as well. I think we can add all three versions: 2018, 2019, and 2020. What do you think?
> 
> Cool. But are we using the 2018 version for any specific analysis? Maybe just 2019 and 2020 versions isn't good enough?

Riiiight. Running correct version might be tricky then. Also it needs to connect to license server and requires an open port, iirc.

**Comment by hassanfa** [comment]
Mergin' to test develop build/push

**Pull request merged**
